.PHONY: clean All

All:
	@echo "----------Building project:[ RWA-I - Debug ]----------"
	@cd "RWA-I" && "$(MAKE)" -f  "RWA-I.mk"
clean:
	@echo "----------Cleaning project:[ RWA-I - Debug ]----------"
	@cd "RWA-I" && "$(MAKE)" -f  "RWA-I.mk" clean
