.PHONY: clean All

All:
	@echo "----------Building project:[ RWA-II - Debug ]----------"
	@cd "RWA-II" && "$(MAKE)" -f  "RWA-II.mk"
clean:
	@echo "----------Cleaning project:[ RWA-II - Debug ]----------"
	@cd "RWA-II" && "$(MAKE)" -f  "RWA-II.mk" clean
